---
- name: load distribution release specific vars
  with_first_found:
    - '../vars/distribution-release/{{ ansible_distribution_release }}.yml'
    - '../vars/distribution-release/default.yml'
  include_vars: '{{ item }}'

- name: install zram-config
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ zram_config_packages }}'
