---
- name: load distribution release specific vars
  with_first_found:
    - '../vars/distribution-release/{{ ansible_distribution_release }}.yml'
    - '../vars/distribution-release/default.yml'
  include_vars: '{{ item }}'

- name: install zram-config
  become: yes
  apt:
    name: '{{ zram_config_packages }}'
    state: present

- name: write sysctl config
  become: yes
  template:
    src: 20-ansible-zram.conf.j2
    dest: /etc/sysctl.d/20-ansible-zram.conf
    owner: root
    group: root
    mode: u=rw,go=r
